import os
from dotenv import load_dotenv

load_dotenv()

GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
GITHUB_REDIRECT_URI = os.getenv("GITHUB_REDIRECT_URI")
GITHUB_ACCESS_TOKEN_URL = os.getenv("GITHUB_ACCESS_TOKEN_URL")
GITHUB_AUTHORIZATION_URL = os.getenv("GITHUB_AUTHORIZATION_URL")
GITHUB_USER_INFO_URL = os.getenv("GITHUB_USER_INFO_URL")
HF_TOKEN = os.getenv("HF_TOKEN")